name: image

on:
  push:
    branches:
      - master

env:
  BUILDROOT_VERSION: '2020.02.1'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        board:
          - 'raspberrypi3'
          - 'raspberrypi4_64'
      fail-fast: false

    env:
      BUILD_NAME: 'dvbheadend-${{ matrix.board }}-${{ github.sha }}'
      CONFIG_NAME: 'dvbheadend_${{ matrix.board }}_defconfig'
    steps:
      - name: Checkout Buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '${{ env.BUILDROOT_VERSION }}'
          path: 'buildroot'

      - name: Checkout External
        uses: actions/checkout@v2
        with:
          path: 'external'
      - name: Configure Image
        run: 'make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/external $CONFIG_NAME'
        working-directory: 'buildroot'

      - name: Cache Downloads
        uses: actions/cache@v1
        with:
          path: 'buildroot/dl'
          key: 'dl-${{ env.BUILDROOT_VERSION }}-${{ matrix.board }}'
      - name: Download Source
        run: 'make -s source'
        working-directory: 'buildroot'

      - name: Build Toolchain
        run: 'make -s toolchain'
        working-directory: 'buildroot'

      - name: Build Image
        run: 'make -s all'
        working-directory: 'buildroot'

      - name: Collect Artifacts
        run: |
          mkdir -p "artifacts/$BUILD_NAME"
          mv buildroot/output/images/sdcard.img buildroot/output/images/*Image artifacts/$BUILD_NAME/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: '${{ env.BUILD_NAME }}'
          path: 'artifacts/${{ env.BUILD_NAME }}'
