name: image

on:
  push:
    branches:
      - master

env:
  BUILDROOT_VERSION: '2020.02.1'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        board:
          - 'raspberrypi3'
          - 'raspberrypi4_64'
      fail-fast: false

    steps:
      - name: Checkout Buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '${{ env.BUILDROOT_VERSION }}'
          path: 'buildroot'

      - name: Checkout Dvbheadend
        uses: actions/checkout@v2
        with:
          path: 'dvbheadend'
      - name: Configure Image
        run: 'make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/dvbheadend dvbheadend_${{ matrix.board }}_defconfig'
        working-directory: 'buildroot'

      - name: Cache Downloads
        uses: actions/cache@v1
        with:
          path: 'buildroot/dl'
          key: 'sources-${{ env.BUILDROOT_VERSION }}-${{ matrix.board }}'
      - name: Download Source
        run: 'make -s source'
        working-directory: 'buildroot'

      - name: Build Toolchain
        run: 'make -s toolchain'
        working-directory: 'buildroot'

      - name: Build Image
        run: 'make -s all'
        working-directory: 'buildroot'

      - name: Upload Image
        uses: actions/upload-artifact@v1
        with:
          name: 'dvbheadend-${{ matrix.board }}-${{ github.sha }}.img'
          path: 'buildroot/output/images/sdcard.img'
