name: image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dvbheadend
        uses: actions/checkout@v2
        with:
          path: 'dvbheadend'
      - name: Checkout buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '2020.02.1'
          path: 'buildroot'

      - name: make dvbheadend_raspberrypi3_defconfig
        run: make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/dvbheadend dvbheadend_raspberrypi3_defconfig
        working-directory: ./buildroot
      - name: make source
        run: make -s source
        working-directory: ./buildroot
      - name: make toolchain
        run: make -s toolchain
        working-directory: ./buildroot
      - name: make all
        run: make -s all
        working-directory: ./buildroot

      - name: Upload images
        uses: actions/upload-artifact@v1
        with:
          name: sdcard.img
          path: buildroot/output/images/sdcard.img
