name: image

on:
  push:
    branches:
      - master

env:
  BUILDROOT_VERSION: '2020.05.1'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        board:
          - 'raspberrypi4_64'
      fail-fast: false

    env:
      BUILD_NAME: 'dvbheadend-${{ matrix.board }}-${{ github.sha }}'
      CONFIG_NAME: 'dvbheadend_${{ matrix.board }}_defconfig'
    steps:
      - name: Free space on runner
        run: |
          #sudo apt-get -y --autoremove remove 'clang*' 'libclang*' 'llvm-*' 'lld-*' 'lldb-*' 'dotnet-*' 'msbuild*' 'mono*' 'libmono*' ca-certificates-mono esl-erlang 'gfortran-*' 'libgfortran*' google-cloud-sdk 'ghc-*' 'cabal-*' 'zulu-*' 'mongodb-org*'
          #sudo apt-get clean
          sudo rm -rf /usr/share/swift /usr/share/dotnet

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install bc

      - name: Checkout Buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '${{ env.BUILDROOT_VERSION }}'
          path: 'buildroot'

      - name: Checkout external
        uses: actions/checkout@v2
        with:
          path: 'external'
      - name: Configure Image
        run: |
          make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/external $CONFIG_NAME
        working-directory: 'buildroot'

      - name: Download source
        run: |
          make -s source
        working-directory: 'buildroot'

      - name: Build image
        run: |
          make -s all
        working-directory: 'buildroot'

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: '${{ env.BUILD_NAME }}'
          path: 'buildroot/output/images/sdcard.img'
